#!/usr/bin/env python3
"""
Helper script to generate SFSU subjects SQL insert statements.
This can be used to add more subjects or verify the list.
"""

def create_slug(name):
    """Convert subject name to URL-friendly slug."""
    slug = name.lower()
    # Replace spaces with hyphens
    slug = slug.replace(' ', '-')
    # Remove special characters (keep hyphens)
    slug = ''.join(c if c.isalnum() or c == '-' else '' for c in slug)
    # Remove multiple consecutive hyphens
    while '--' in slug:
        slug = slug.replace('--', '-')
    # Remove leading/trailing hyphens
    slug = slug.strip('-')
    return slug

# Comprehensive SFSU subjects list
SFSU_SUBJECTS = [
    # Sciences
    'Biology', 'Chemistry', 'Computer Science', 'Mathematics', 'Physics',
    'Astronomy', 'Geosciences', 'Environmental Studies',
    
    # Engineering & Technology
    'Engineering', 'Electrical Engineering', 'Mechanical Engineering',
    'Information Systems',
    
    # Business & Economics
    'Accounting', 'Business Administration', 'Economics', 'Finance',
    'International Business', 'Management', 'Marketing', 'Entrepreneurship',
    
    # Social Sciences
    'Anthropology', 'Criminal Justice', 'Geography', 'History',
    'International Relations', 'Political Science', 'Psychology',
    'Sociology', 'Urban Studies',
    
    # Humanities & Arts
    'Art', 'Art History', 'Cinema', 'Communication Studies',
    'Comparative Literature', 'Creative Writing', 'English',
    'Foreign Languages', 'French', 'German', 'Italian', 'Japanese',
    'Spanish', 'Chinese', 'Hebrew', 'Modern Greek', 'Philosophy',
    'Religious Studies', 'Theatre Arts', 'Music', 'Dance',
    
    # Education
    'Education', 'Elementary Education', 'Secondary Education',
    'Special Education',
    
    # Health & Kinesiology
    'Health Education', 'Kinesiology', 'Nursing',
    'Recreation, Parks, and Tourism', 'Public Health',
    
    # Journalism & Media
    'Journalism', 'Broadcast and Electronic Communication Arts',
    'Visual Communication Design',
    
    # Ethnic & Area Studies
    'Africana Studies', 'American Indian Studies', 'Asian American Studies',
    'Chicana and Latina/o Studies', 'Race and Resistance Studies',
    'Women and Gender Studies', 'Ethnic Studies',
    
    # Other
    'Humanities', 'Liberal Studies', 'Public Administration',
    'Social Work', 'Consumer and Family Studies', 'Consumer Affairs',
    'Hospitality and Tourism Management', 'Child and Adolescent Development',
    'Interdisciplinary Studies', 'Holistic Health',
]

def generate_sql():
    """Generate SQL INSERT statements."""
    print("-- Seed SFSU academic subjects/departments")
    print("-- Generated by generate_sfsu_subjects.py\n")
    print("INSERT INTO subjects (name, slug) VALUES")
    
    values = []
    for subject in sorted(SFSU_SUBJECTS):
        slug = create_slug(subject)
        values.append(f"('{subject}', '{slug}')")
    
    print(",\n".join(values))
    print("ON DUPLICATE KEY UPDATE name=VALUES(name);")

if __name__ == '__main__':
    generate_sql()

