#!/usr/bin/env python3
"""
sfsu_courses_data.py
--------------------
Course data for Science and Engineering departments at SFSU.
Part 1 of 3 data files used by update_courses.py.

Contributors: Ranjiv Jithendran
"""

# Format: (department, course_number, title, description, level, credits, prerequisites, subject_slug)

# =============================================
# COLLEGE OF SCIENCE & ENGINEERING
# =============================================

CSC_COURSES = [
    ('CSC', '101', 'Computers for Everyone', 'Introduction to computing concepts for non-majors.', 'undergraduate', 3, None, 'computer-science'),
    ('CSC', '110', 'Computational Thinking', 'Problem solving with computational approaches.', 'undergraduate', 3, None, 'computer-science'),
    ('CSC', '165', 'Python for Everyone', 'Introduction to Python programming for non-majors.', 'undergraduate', 3, None, 'computer-science'),
    ('CSC', '200', 'Software Development Lifecycle', 'Overview of software development processes.', 'undergraduate', 3, None, 'computer-science'),
    ('CSC', '210', 'Introduction to Computer Programming', 'Fundamentals of programming using Python.', 'undergraduate', 3, 'MATH 124', 'computer-science'),
    ('CSC', '211', 'Programming with Data Structures', 'Object-oriented programming and basic data structures.', 'undergraduate', 3, 'CSC 210', 'computer-science'),
    ('CSC', '215', 'Computer Architecture', 'Computer organization and hardware fundamentals.', 'undergraduate', 3, 'CSC 210', 'computer-science'),
    ('CSC', '220', 'Data Structures', 'Trees, graphs, hash tables, and algorithm analysis.', 'undergraduate', 3, 'CSC 211', 'computer-science'),
    ('CSC', '230', 'Discrete Mathematical Structures', 'Logic, sets, functions, and combinatorics.', 'undergraduate', 3, 'CSC 210', 'computer-science'),
    ('CSC', '256', 'Machine Structures', 'Assembly language and computer organization.', 'undergraduate', 3, 'CSC 220', 'computer-science'),
    ('CSC', '300', 'Social Computing', 'Social media, crowdsourcing, and online communities.', 'undergraduate', 3, 'CSC 210', 'computer-science'),
    ('CSC', '307', 'iPhone App Development', 'iOS application development with Swift.', 'undergraduate', 3, 'CSC 210', 'computer-science'),
    ('CSC', '308', 'Android App Development', 'Android application development.', 'undergraduate', 3, 'CSC 210', 'computer-science'),
    ('CSC', '309', 'Cross-Platform Mobile Development', 'Mobile app development for multiple platforms.', 'undergraduate', 3, 'CSC 210', 'computer-science'),
    ('CSC', '317', 'Introduction to Web Software Development', 'HTML, CSS, JavaScript, and server-side programming.', 'undergraduate', 3, 'CSC 210', 'computer-science'),
    ('CSC', '340', 'Programming Methodology', 'Design patterns, testing, and software engineering.', 'undergraduate', 3, 'CSC 256', 'computer-science'),
    ('CSC', '345', 'Introduction to Data Science', 'Data analysis, visualization, and machine learning basics.', 'undergraduate', 3, 'CSC 220', 'computer-science'),
    ('CSC', '410', 'Introduction to Compilers', 'Lexical analysis, parsing, and code generation.', 'undergraduate', 3, 'CSC 340', 'computer-science'),
    ('CSC', '413', 'Software Development', 'Agile methodologies and team-based software projects.', 'undergraduate', 3, 'CSC 340', 'computer-science'),
    ('CSC', '415', 'Operating Systems Principles', 'Process management, memory, and file systems.', 'undergraduate', 3, 'CSC 340', 'computer-science'),
    ('CSC', '415', 'Computer Security', 'Security principles, cryptography, and vulnerabilities.', 'undergraduate', 3, 'CSC 340', 'computer-science'),
    ('CSC', '510', 'Analysis of Algorithms I', 'Algorithm design and complexity analysis.', 'undergraduate', 3, 'CSC 220', 'computer-science'),
    ('CSC', '520', 'Theory of Computing', 'Automata, formal languages, and computability.', 'undergraduate', 3, 'CSC 230', 'computer-science'),
    ('CSC', '600', 'Programming Language Design', 'Syntax, semantics, and language implementation.', 'graduate', 3, 'CSC 340', 'computer-science'),
    ('CSC', '615', 'Database Systems', 'SQL, normalization, and transaction processing.', 'undergraduate', 3, 'CSC 340', 'computer-science'),
    ('CSC', '620', 'Data Mining', 'Classification, clustering, and association rules.', 'graduate', 3, 'CSC 510', 'computer-science'),
    ('CSC', '621', 'Machine Learning', 'Supervised and unsupervised learning algorithms.', 'graduate', 3, 'CSC 510', 'computer-science'),
    ('CSC', '622', 'Deep Learning', 'Neural networks and deep learning architectures.', 'graduate', 3, 'CSC 621', 'computer-science'),
    ('CSC', '630', 'Computer Graphics', 'Rendering, transformations, and OpenGL.', 'graduate', 3, 'CSC 340', 'computer-science'),
    ('CSC', '631', 'Multiplayer Game Development', 'Networked games and game engines.', 'graduate', 3, 'CSC 340', 'computer-science'),
    ('CSC', '635', 'Natural Language Processing', 'Text processing and language understanding.', 'graduate', 3, 'CSC 510', 'computer-science'),
    ('CSC', '642', 'Human-Computer Interaction', 'User interface design and usability.', 'graduate', 3, 'CSC 340', 'computer-science'),
    ('CSC', '645', 'Computer Networks', 'TCP/IP, routing, and network protocols.', 'undergraduate', 3, 'CSC 340', 'computer-science'),
    ('CSC', '648', 'Software Engineering', 'Full-stack development with team projects.', 'graduate', 3, 'CSC 340', 'computer-science'),
    ('CSC', '650', 'Operating Systems', 'Advanced OS concepts and implementation.', 'graduate', 3, 'CSC 415', 'computer-science'),
    ('CSC', '656', 'Computer Graphics', 'Advanced graphics and visualization.', 'undergraduate', 3, 'CSC 340', 'computer-science'),
    ('CSC', '665', 'Artificial Intelligence', 'Search, knowledge representation, and learning.', 'undergraduate', 3, 'CSC 510', 'computer-science'),
    ('CSC', '667', 'Internet Application Development', 'Advanced web applications and cloud deployment.', 'graduate', 3, 'CSC 317', 'computer-science'),
    ('CSC', '668', 'Advanced Software Engineering', 'Software architecture and DevOps.', 'graduate', 3, 'CSC 648', 'computer-science'),
    ('CSC', '670', 'Computer Security', 'Advanced security topics and cryptography.', 'graduate', 3, 'CSC 340', 'computer-science'),
    ('CSC', '675', 'Introduction to Database Systems', 'Database design and administration.', 'graduate', 3, 'CSC 340', 'computer-science'),
    ('CSC', '680', 'Cloud Computing', 'Cloud architectures and distributed systems.', 'graduate', 3, 'CSC 340', 'computer-science'),
    ('CSC', '690', 'Interactive Multimedia', 'Multimedia systems and applications.', 'graduate', 3, 'CSC 340', 'computer-science'),
    ('CSC', '693', 'Research Project', 'Independent research project.', 'graduate', 3, None, 'computer-science'),
    ('CSC', '695', 'Topics in Computer Science', 'Special topics vary by semester.', 'graduate', 3, None, 'computer-science'),
    ('CSC', '700', 'Culminating Experience Prep', 'Thesis or project preparation.', 'graduate', 3, None, 'computer-science'),
    ('CSC', '895', "Master's Thesis", 'Independent thesis research.', 'graduate', 6, 'CSC 700', 'computer-science'),
    ('CSC', '898', "Master's Project", 'Culminating project.', 'graduate', 3, 'CSC 700', 'computer-science'),
]

MATH_COURSES = [
    ('MATH', '60', 'Preparation for Algebra', 'Fundamental math skills.', 'undergraduate', 3, None, 'mathematics'),
    ('MATH', '70', 'Algebra Foundations', 'Linear equations and polynomials.', 'undergraduate', 3, None, 'mathematics'),
    ('MATH', '75', 'Elementary Algebra', 'Basic algebraic operations.', 'undergraduate', 3, None, 'mathematics'),
    ('MATH', '99', 'Pre-Statistics', 'Preparation for statistics courses.', 'undergraduate', 3, None, 'mathematics'),
    ('MATH', '109', 'Number Sense', 'Mathematical reasoning for educators.', 'undergraduate', 3, None, 'mathematics'),
    ('MATH', '110', 'Business Calculus', 'Calculus for business applications.', 'undergraduate', 3, 'MATH 70', 'mathematics'),
    ('MATH', '124', 'Elementary Statistics', 'Descriptive statistics and probability.', 'undergraduate', 3, None, 'mathematics'),
    ('MATH', '165', 'Finite Mathematics', 'Sets, matrices, and linear programming.', 'undergraduate', 3, 'MATH 70', 'mathematics'),
    ('MATH', '197', 'Prelude to Calculus', 'Functions and trigonometry.', 'undergraduate', 3, 'MATH 70', 'mathematics'),
    ('MATH', '199', 'Pre-Calculus', 'Functions, trigonometry, and analytic geometry.', 'undergraduate', 4, 'MATH 70', 'mathematics'),
    ('MATH', '226', 'Calculus I', 'Limits, derivatives, and applications.', 'undergraduate', 4, 'MATH 199', 'mathematics'),
    ('MATH', '227', 'Calculus II', 'Integration and infinite series.', 'undergraduate', 4, 'MATH 226', 'mathematics'),
    ('MATH', '228', 'Calculus III', 'Multivariable calculus.', 'undergraduate', 4, 'MATH 227', 'mathematics'),
    ('MATH', '245', 'Elementary Differential Equations', 'First and second order equations.', 'undergraduate', 3, 'MATH 227', 'mathematics'),
    ('MATH', '270', 'Mathematics for Future Elementary Teachers', 'Math concepts for teaching.', 'undergraduate', 3, None, 'mathematics'),
    ('MATH', '301', 'Exploration and Proof', 'Introduction to mathematical proofs.', 'undergraduate', 3, 'MATH 227', 'mathematics'),
    ('MATH', '310', 'Linear Algebra I', 'Vector spaces and linear transformations.', 'undergraduate', 3, 'MATH 227', 'mathematics'),
    ('MATH', '325', 'Linear Algebra', 'Matrices, eigenvalues, and applications.', 'undergraduate', 3, 'MATH 227', 'mathematics'),
    ('MATH', '335', 'Discrete Mathematics', 'Combinatorics and graph theory.', 'undergraduate', 3, 'MATH 227', 'mathematics'),
    ('MATH', '338', 'History of Mathematics', 'Development of mathematical ideas.', 'undergraduate', 3, 'MATH 301', 'mathematics'),
    ('MATH', '370', 'Real Analysis I', 'Rigorous treatment of real numbers.', 'undergraduate', 3, 'MATH 301', 'mathematics'),
    ('MATH', '371', 'Real Analysis II', 'Advanced topics in analysis.', 'undergraduate', 3, 'MATH 370', 'mathematics'),
    ('MATH', '376', 'Optimization', 'Linear and nonlinear optimization.', 'undergraduate', 3, 'MATH 325', 'mathematics'),
    ('MATH', '380', 'Complex Analysis', 'Functions of complex variables.', 'undergraduate', 3, 'MATH 370', 'mathematics'),
    ('MATH', '435', 'Modern Algebra I', 'Groups, rings, and fields.', 'undergraduate', 3, 'MATH 301', 'mathematics'),
    ('MATH', '436', 'Modern Algebra II', 'Advanced abstract algebra.', 'undergraduate', 3, 'MATH 435', 'mathematics'),
    ('MATH', '440', 'Probability and Statistics', 'Probability theory and inference.', 'undergraduate', 3, 'MATH 228', 'mathematics'),
    ('MATH', '441', 'Mathematical Statistics', 'Statistical theory and methods.', 'undergraduate', 3, 'MATH 440', 'mathematics'),
    ('MATH', '449', 'Complex Variables', 'Analytic functions and integration.', 'undergraduate', 3, 'MATH 228', 'mathematics'),
    ('MATH', '450', 'Geometry', 'Euclidean and non-Euclidean geometry.', 'undergraduate', 3, 'MATH 301', 'mathematics'),
    ('MATH', '460', 'Number Theory', 'Divisibility and prime numbers.', 'undergraduate', 3, 'MATH 301', 'mathematics'),
    ('MATH', '470', 'Numerical Analysis I', 'Numerical methods for computation.', 'undergraduate', 3, 'MATH 325', 'mathematics'),
    ('MATH', '471', 'Numerical Analysis II', 'Advanced numerical methods.', 'undergraduate', 3, 'MATH 470', 'mathematics'),
    ('MATH', '510', 'Applied Partial Differential Equations', 'PDEs and applications.', 'undergraduate', 3, 'MATH 245', 'mathematics'),
    ('MATH', '520', 'Combinatorics', 'Advanced combinatorial methods.', 'undergraduate', 3, 'MATH 335', 'mathematics'),
    ('MATH', '600', 'Seminar in Mathematics', 'Graduate seminar.', 'graduate', 3, None, 'mathematics'),
    ('MATH', '700', 'Thesis', 'Graduate thesis research.', 'graduate', 6, None, 'mathematics'),
]

PHYS_COURSES = [
    ('PHYS', '100', 'Concepts of Physics', 'Physics for non-science majors.', 'undergraduate', 3, None, 'physics'),
    ('PHYS', '101', 'Energy and the Environment', 'Physics of energy and sustainability.', 'undergraduate', 3, None, 'physics'),
    ('PHYS', '111', 'General Physics I', 'Algebra-based mechanics and heat.', 'undergraduate', 3, 'MATH 70', 'physics'),
    ('PHYS', '112', 'General Physics II', 'Algebra-based electricity and magnetism.', 'undergraduate', 3, 'PHYS 111', 'physics'),
    ('PHYS', '121', 'Physics Laboratory I', 'Mechanics laboratory.', 'undergraduate', 1, 'PHYS 111', 'physics'),
    ('PHYS', '122', 'Physics Laboratory II', 'E&M laboratory.', 'undergraduate', 1, 'PHYS 112', 'physics'),
    ('PHYS', '220', 'General Physics with Calculus I', 'Calculus-based mechanics.', 'undergraduate', 4, 'MATH 226', 'physics'),
    ('PHYS', '222', 'General Physics with Calculus II', 'Calculus-based E&M.', 'undergraduate', 4, 'PHYS 220', 'physics'),
    ('PHYS', '230', 'Modern Physics', 'Relativity and quantum mechanics.', 'undergraduate', 3, 'PHYS 222', 'physics'),
    ('PHYS', '240', 'Computational Physics', 'Numerical methods for physics.', 'undergraduate', 3, 'PHYS 222', 'physics'),
    ('PHYS', '300', 'Experimental Physics I', 'Advanced laboratory techniques.', 'undergraduate', 3, 'PHYS 230', 'physics'),
    ('PHYS', '301', 'Experimental Physics II', 'Advanced experiments.', 'undergraduate', 3, 'PHYS 300', 'physics'),
    ('PHYS', '320', 'Analytical Mechanics', 'Lagrangian and Hamiltonian mechanics.', 'undergraduate', 3, 'PHYS 230', 'physics'),
    ('PHYS', '330', 'Thermal Physics', 'Thermodynamics and statistical mechanics.', 'undergraduate', 3, 'PHYS 230', 'physics'),
    ('PHYS', '350', 'Electronics for Scientists', 'Electronics for research.', 'undergraduate', 3, 'PHYS 222', 'physics'),
    ('PHYS', '360', 'Electromagnetism', 'Maxwell equations and waves.', 'undergraduate', 3, 'PHYS 222', 'physics'),
    ('PHYS', '385', 'Quantum Mechanics', 'Wave mechanics and applications.', 'undergraduate', 3, 'PHYS 230', 'physics'),
    ('PHYS', '410', 'Electromagnetic Theory', 'Advanced electromagnetism.', 'undergraduate', 3, 'PHYS 360', 'physics'),
    ('PHYS', '420', 'Atomic and Molecular Physics', 'Atomic structure and spectra.', 'undergraduate', 3, 'PHYS 385', 'physics'),
    ('PHYS', '430', 'Nuclear and Particle Physics', 'Nuclear structure and particles.', 'undergraduate', 3, 'PHYS 385', 'physics'),
    ('PHYS', '440', 'Solid State Physics', 'Crystal structure and properties.', 'undergraduate', 3, 'PHYS 385', 'physics'),
    ('PHYS', '480', 'Astrophysics', 'Stars, galaxies, and cosmology.', 'undergraduate', 3, 'PHYS 230', 'physics'),
    ('PHYS', '490', 'Advanced Quantum Mechanics', 'Advanced QM topics.', 'undergraduate', 3, 'PHYS 385', 'physics'),
    ('PHYS', '600', 'Graduate Physics', 'Graduate-level physics.', 'graduate', 3, None, 'physics'),
    ('PHYS', '700', 'Thesis', 'Graduate thesis research.', 'graduate', 6, None, 'physics'),
]

CHEM_COURSES = [
    ('CHEM', '100', 'Chemistry and Society', 'Chemistry for non-majors.', 'undergraduate', 3, None, 'chemistry'),
    ('CHEM', '101', 'Chemistry and Our Society', 'Environmental chemistry.', 'undergraduate', 3, None, 'chemistry'),
    ('CHEM', '102', 'Introductory Chemistry', 'Basic chemistry concepts.', 'undergraduate', 4, None, 'chemistry'),
    ('CHEM', '115', 'General Chemistry I', 'Atomic structure and bonding.', 'undergraduate', 4, 'MATH 70', 'chemistry'),
    ('CHEM', '116', 'General Chemistry II', 'Equilibrium and thermodynamics.', 'undergraduate', 4, 'CHEM 115', 'chemistry'),
    ('CHEM', '130', 'Survey of Organic and Biological Chemistry', 'Organic chemistry for health sciences.', 'undergraduate', 4, 'CHEM 102', 'chemistry'),
    ('CHEM', '215', 'Quantitative Analysis', 'Analytical chemistry techniques.', 'undergraduate', 4, 'CHEM 116', 'chemistry'),
    ('CHEM', '235', 'Organic Chemistry I', 'Structure and reactions.', 'undergraduate', 3, 'CHEM 116', 'chemistry'),
    ('CHEM', '236', 'Organic Chemistry II', 'Advanced organic reactions.', 'undergraduate', 3, 'CHEM 235', 'chemistry'),
    ('CHEM', '237', 'Organic Chemistry Laboratory I', 'Organic lab techniques.', 'undergraduate', 2, 'CHEM 235', 'chemistry'),
    ('CHEM', '238', 'Organic Chemistry Laboratory II', 'Advanced organic lab.', 'undergraduate', 2, 'CHEM 236', 'chemistry'),
    ('CHEM', '340', 'Biochemistry', 'Biological molecules and metabolism.', 'undergraduate', 3, 'CHEM 236', 'chemistry'),
    ('CHEM', '341', 'Biochemistry Laboratory', 'Biochemistry lab techniques.', 'undergraduate', 2, 'CHEM 340', 'chemistry'),
    ('CHEM', '350', 'Physical Chemistry I', 'Thermodynamics and kinetics.', 'undergraduate', 3, 'CHEM 116', 'chemistry'),
    ('CHEM', '351', 'Physical Chemistry II', 'Quantum chemistry.', 'undergraduate', 3, 'CHEM 350', 'chemistry'),
    ('CHEM', '352', 'Physical Chemistry Laboratory', 'P-chem experiments.', 'undergraduate', 2, 'CHEM 350', 'chemistry'),
    ('CHEM', '410', 'Instrumental Analysis', 'Spectroscopy and chromatography.', 'undergraduate', 4, 'CHEM 215', 'chemistry'),
    ('CHEM', '420', 'Inorganic Chemistry', 'Coordination and organometallic chemistry.', 'undergraduate', 3, 'CHEM 351', 'chemistry'),
    ('CHEM', '430', 'Advanced Organic Chemistry', 'Mechanisms and synthesis.', 'undergraduate', 3, 'CHEM 236', 'chemistry'),
    ('CHEM', '450', 'Advanced Biochemistry', 'Enzymes and metabolism.', 'undergraduate', 3, 'CHEM 340', 'chemistry'),
    ('CHEM', '600', 'Graduate Chemistry', 'Graduate-level chemistry.', 'graduate', 3, None, 'chemistry'),
    ('CHEM', '700', 'Thesis', 'Graduate thesis research.', 'graduate', 6, None, 'chemistry'),
]

BIOL_COURSES = [
    ('BIOL', '100', 'Introduction to Biology', 'Biology for non-majors.', 'undergraduate', 3, None, 'biology'),
    ('BIOL', '101', 'Human Biology', 'Human anatomy for non-majors.', 'undergraduate', 3, None, 'biology'),
    ('BIOL', '110', 'Environmental Biology', 'Ecology and environment.', 'undergraduate', 3, None, 'biology'),
    ('BIOL', '180', 'Nutrition', 'Fundamentals of nutrition.', 'undergraduate', 3, None, 'biology'),
    ('BIOL', '230', 'Principles of Biology I', 'Cell and molecular biology.', 'undergraduate', 4, 'CHEM 115', 'biology'),
    ('BIOL', '231', 'Principles of Biology II', 'Evolution and ecology.', 'undergraduate', 4, 'BIOL 230', 'biology'),
    ('BIOL', '240', 'Biostatistics', 'Statistics for biology.', 'undergraduate', 3, 'BIOL 230', 'biology'),
    ('BIOL', '310', 'Comparative Anatomy', 'Vertebrate anatomy.', 'undergraduate', 4, 'BIOL 231', 'biology'),
    ('BIOL', '325', 'Invertebrate Zoology', 'Invertebrate biology.', 'undergraduate', 4, 'BIOL 231', 'biology'),
    ('BIOL', '330', 'Genetics', 'Mendelian and molecular genetics.', 'undergraduate', 3, 'BIOL 230', 'biology'),
    ('BIOL', '332', 'Genetics Laboratory', 'Genetics experiments.', 'undergraduate', 2, 'BIOL 330', 'biology'),
    ('BIOL', '335', 'Molecular Biology', 'Gene expression and regulation.', 'undergraduate', 3, 'BIOL 330', 'biology'),
    ('BIOL', '337', 'Molecular Biology Laboratory', 'Molecular techniques.', 'undergraduate', 2, 'BIOL 335', 'biology'),
    ('BIOL', '340', 'Botany', 'Plant biology.', 'undergraduate', 4, 'BIOL 231', 'biology'),
    ('BIOL', '350', 'Microbiology', 'Microorganisms and pathogens.', 'undergraduate', 4, 'BIOL 230', 'biology'),
    ('BIOL', '355', 'Cell Biology', 'Cell structure and function.', 'undergraduate', 3, 'BIOL 230', 'biology'),
    ('BIOL', '360', 'Developmental Biology', 'Embryology and development.', 'undergraduate', 3, 'BIOL 355', 'biology'),
    ('BIOL', '370', 'Animal Physiology', 'Comparative physiology.', 'undergraduate', 4, 'BIOL 231', 'biology'),
    ('BIOL', '380', 'Human Anatomy', 'Human anatomical structures.', 'undergraduate', 4, 'BIOL 230', 'biology'),
    ('BIOL', '385', 'Human Physiology', 'Human body functions.', 'undergraduate', 4, 'BIOL 380', 'biology'),
    ('BIOL', '410', 'Ecology', 'Population and community ecology.', 'undergraduate', 3, 'BIOL 231', 'biology'),
    ('BIOL', '412', 'Ecology Laboratory', 'Field ecology methods.', 'undergraduate', 2, 'BIOL 410', 'biology'),
    ('BIOL', '420', 'Evolution', 'Evolutionary mechanisms.', 'undergraduate', 3, 'BIOL 330', 'biology'),
    ('BIOL', '430', 'Marine Biology', 'Ocean ecosystems and organisms.', 'undergraduate', 3, 'BIOL 231', 'biology'),
    ('BIOL', '440', 'Immunology', 'Immune system function.', 'undergraduate', 3, 'BIOL 350', 'biology'),
    ('BIOL', '450', 'Virology', 'Virus biology and disease.', 'undergraduate', 3, 'BIOL 350', 'biology'),
    ('BIOL', '460', 'Neurobiology', 'Nervous system biology.', 'undergraduate', 3, 'BIOL 370', 'biology'),
    ('BIOL', '470', 'Bioinformatics', 'Computational biology.', 'undergraduate', 3, 'BIOL 335', 'biology'),
    ('BIOL', '480', 'Conservation Biology', 'Biodiversity conservation.', 'undergraduate', 3, 'BIOL 410', 'biology'),
    ('BIOL', '600', 'Graduate Biology', 'Graduate-level biology.', 'graduate', 3, None, 'biology'),
    ('BIOL', '700', 'Thesis', 'Graduate thesis research.', 'graduate', 6, None, 'biology'),
]

ENGR_COURSES = [
    ('ENGR', '100', 'Introduction to Engineering', 'Engineering overview.', 'undergraduate', 3, None, 'engineering'),
    ('ENGR', '101', 'Engineering Graphics', 'Technical drawing and CAD.', 'undergraduate', 2, None, 'engineering'),
    ('ENGR', '102', 'Engineering Problem Solving', 'Problem-solving methods.', 'undergraduate', 3, 'MATH 199', 'engineering'),
    ('ENGR', '200', 'Engineering Statics', 'Forces and equilibrium.', 'undergraduate', 3, 'PHYS 220', 'engineering'),
    ('ENGR', '201', 'Engineering Dynamics', 'Kinematics and kinetics.', 'undergraduate', 3, 'ENGR 200', 'engineering'),
    ('ENGR', '205', 'Materials Science', 'Engineering materials.', 'undergraduate', 3, 'CHEM 115', 'engineering'),
    ('ENGR', '210', 'Circuit Analysis', 'DC and AC circuits.', 'undergraduate', 3, 'PHYS 222', 'engineering'),
    ('ENGR', '300', 'Mechanics of Solids', 'Stress and deformation.', 'undergraduate', 3, 'ENGR 200', 'engineering'),
    ('ENGR', '302', 'Thermodynamics', 'Energy and heat transfer.', 'undergraduate', 3, 'PHYS 220', 'engineering'),
    ('ENGR', '303', 'Fluid Mechanics', 'Fluid statics and dynamics.', 'undergraduate', 3, 'ENGR 201', 'engineering'),
    ('ENGR', '309', 'Manufacturing Processes', 'Manufacturing methods.', 'undergraduate', 3, 'ENGR 205', 'engineering'),
    ('ENGR', '320', 'Engineering Economics', 'Economic analysis for engineering.', 'undergraduate', 3, None, 'engineering'),
    ('ENGR', '330', 'Measurements and Instrumentation', 'Measurement techniques.', 'undergraduate', 3, 'ENGR 210', 'engineering'),
    ('ENGR', '350', 'Engineering Design I', 'Design methodology.', 'undergraduate', 3, 'ENGR 300', 'engineering'),
    ('ENGR', '351', 'Engineering Design II', 'Capstone design project.', 'undergraduate', 3, 'ENGR 350', 'engineering'),
    ('ENGR', '400', 'Finite Element Analysis', 'FEA methods and applications.', 'undergraduate', 3, 'ENGR 300', 'engineering'),
    ('ENGR', '410', 'Control Systems', 'Feedback and control.', 'undergraduate', 3, 'ENGR 210', 'engineering'),
    ('ENGR', '420', 'Heat Transfer', 'Conduction, convection, radiation.', 'undergraduate', 3, 'ENGR 302', 'engineering'),
    ('ENGR', '430', 'Machine Design', 'Mechanical component design.', 'undergraduate', 3, 'ENGR 300', 'engineering'),
    ('ENGR', '440', 'Mechatronics', 'Mechanical-electronic systems.', 'undergraduate', 3, 'ENGR 410', 'engineering'),
    ('ENGR', '450', 'Robotics', 'Robot kinematics and control.', 'undergraduate', 3, 'ENGR 410', 'engineering'),
    ('ENGR', '600', 'Graduate Engineering', 'Graduate-level engineering.', 'graduate', 3, None, 'engineering'),
    ('ENGR', '700', 'Thesis', 'Graduate thesis research.', 'graduate', 6, None, 'engineering'),
]

EE_COURSES = [
    ('EE', '200', 'Introduction to Electrical Engineering', 'EE overview.', 'undergraduate', 3, None, 'electrical-engineering'),
    ('EE', '210', 'Circuits I', 'DC circuit analysis.', 'undergraduate', 3, 'PHYS 222', 'electrical-engineering'),
    ('EE', '211', 'Circuits II', 'AC circuits and frequency response.', 'undergraduate', 3, 'EE 210', 'electrical-engineering'),
    ('EE', '212', 'Circuits Laboratory', 'Circuit experiments.', 'undergraduate', 1, 'EE 211', 'electrical-engineering'),
    ('EE', '310', 'Electronics I', 'Semiconductor devices.', 'undergraduate', 3, 'EE 211', 'electrical-engineering'),
    ('EE', '311', 'Electronics II', 'Amplifier design.', 'undergraduate', 3, 'EE 310', 'electrical-engineering'),
    ('EE', '312', 'Electronics Laboratory', 'Electronics experiments.', 'undergraduate', 1, 'EE 311', 'electrical-engineering'),
    ('EE', '322', 'Signals and Systems', 'Signal processing fundamentals.', 'undergraduate', 3, 'EE 211', 'electrical-engineering'),
    ('EE', '330', 'Electromagnetics', 'EM fields and waves.', 'undergraduate', 3, 'PHYS 222', 'electrical-engineering'),
    ('EE', '350', 'Digital Design', 'Logic gates and circuits.', 'undergraduate', 3, 'EE 210', 'electrical-engineering'),
    ('EE', '351', 'Digital Design Laboratory', 'Digital circuit experiments.', 'undergraduate', 1, 'EE 350', 'electrical-engineering'),
    ('EE', '360', 'Microprocessors', 'Microprocessor architecture.', 'undergraduate', 3, 'EE 350', 'electrical-engineering'),
    ('EE', '410', 'Power Systems', 'Electric power generation.', 'undergraduate', 3, 'EE 211', 'electrical-engineering'),
    ('EE', '420', 'Digital Signal Processing', 'DSP algorithms.', 'undergraduate', 3, 'EE 322', 'electrical-engineering'),
    ('EE', '430', 'Communication Systems', 'Modulation and transmission.', 'undergraduate', 3, 'EE 322', 'electrical-engineering'),
    ('EE', '442', 'Communication Systems', 'Analog and digital communication.', 'undergraduate', 3, 'EE 322', 'electrical-engineering'),
    ('EE', '450', 'VLSI Design', 'Integrated circuit design.', 'undergraduate', 3, 'EE 350', 'electrical-engineering'),
    ('EE', '460', 'Control Systems', 'Feedback control design.', 'undergraduate', 3, 'EE 322', 'electrical-engineering'),
    ('EE', '470', 'Embedded Systems', 'Embedded programming.', 'undergraduate', 3, 'EE 360', 'electrical-engineering'),
    ('EE', '480', 'RF and Microwave Engineering', 'High-frequency circuits.', 'undergraduate', 3, 'EE 330', 'electrical-engineering'),
    ('EE', '600', 'Graduate Electrical Engineering', 'Graduate-level EE.', 'graduate', 3, None, 'electrical-engineering'),
    ('EE', '700', 'Thesis', 'Graduate thesis research.', 'graduate', 6, None, 'electrical-engineering'),
]

GEOL_COURSES = [
    ('GEOL', '100', 'Introduction to Earth Science', 'Earth systems overview.', 'undergraduate', 3, None, 'geosciences'),
    ('GEOL', '101', 'Physical Geology', 'Earth materials and processes.', 'undergraduate', 3, None, 'geosciences'),
    ('GEOL', '102', 'Physical Geology Laboratory', 'Mineral and rock identification.', 'undergraduate', 1, 'GEOL 101', 'geosciences'),
    ('GEOL', '103', 'Historical Geology', 'Earth history and evolution.', 'undergraduate', 3, 'GEOL 101', 'geosciences'),
    ('GEOL', '200', 'Environmental Geology', 'Geologic hazards and resources.', 'undergraduate', 3, None, 'geosciences'),
    ('GEOL', '300', 'Mineralogy', 'Crystal chemistry and mineral identification.', 'undergraduate', 4, 'GEOL 101', 'geosciences'),
    ('GEOL', '310', 'Petrology', 'Rock classification and origin.', 'undergraduate', 4, 'GEOL 300', 'geosciences'),
    ('GEOL', '320', 'Structural Geology', 'Rock deformation and tectonics.', 'undergraduate', 4, 'GEOL 101', 'geosciences'),
    ('GEOL', '330', 'Sedimentology', 'Sedimentary processes and rocks.', 'undergraduate', 4, 'GEOL 101', 'geosciences'),
    ('GEOL', '340', 'Paleontology', 'Fossil record and evolution.', 'undergraduate', 4, 'GEOL 103', 'geosciences'),
    ('GEOL', '350', 'Geomorphology', 'Landform evolution.', 'undergraduate', 4, 'GEOL 101', 'geosciences'),
    ('GEOL', '400', 'Field Geology', 'Field mapping and techniques.', 'undergraduate', 4, 'GEOL 320', 'geosciences'),
    ('GEOL', '410', 'Hydrogeology', 'Groundwater systems.', 'undergraduate', 3, 'GEOL 101', 'geosciences'),
    ('GEOL', '420', 'Geophysics', 'Seismic and gravity methods.', 'undergraduate', 3, 'GEOL 101', 'geosciences'),
    ('GEOL', '430', 'Geochemistry', 'Chemical processes in Earth.', 'undergraduate', 3, 'GEOL 300', 'geosciences'),
    ('GEOL', '440', 'Plate Tectonics', 'Global tectonics.', 'undergraduate', 3, 'GEOL 320', 'geosciences'),
    ('GEOL', '450', 'Volcanology', 'Volcanic processes and hazards.', 'undergraduate', 3, 'GEOL 310', 'geosciences'),
    ('GEOL', '460', 'Seismology', 'Earthquake science.', 'undergraduate', 3, 'GEOL 420', 'geosciences'),
    ('GEOL', '600', 'Graduate Geology', 'Graduate-level geology.', 'graduate', 3, None, 'geosciences'),
    ('GEOL', '700', 'Thesis', 'Graduate thesis research.', 'graduate', 6, None, 'geosciences'),
]

ASTR_COURSES = [
    ('ASTR', '101', 'Introduction to Astronomy', 'Survey of astronomy.', 'undergraduate', 3, None, 'astronomy'),
    ('ASTR', '115', 'Astronomy Laboratory', 'Observational astronomy.', 'undergraduate', 1, 'ASTR 101', 'astronomy'),
    ('ASTR', '201', 'The Solar System', 'Planets and moons.', 'undergraduate', 3, 'ASTR 101', 'astronomy'),
    ('ASTR', '202', 'Stars and Galaxies', 'Stellar evolution and galaxies.', 'undergraduate', 3, 'ASTR 101', 'astronomy'),
    ('ASTR', '300', 'Astrophysics I', 'Physical principles in astronomy.', 'undergraduate', 3, 'PHYS 222', 'astronomy'),
    ('ASTR', '400', 'Cosmology', 'Origin and structure of universe.', 'undergraduate', 3, 'ASTR 300', 'astronomy'),
    ('ASTR', '410', 'Stellar Astrophysics', 'Stellar structure and evolution.', 'undergraduate', 3, 'ASTR 300', 'astronomy'),
    ('ASTR', '420', 'Galactic Astronomy', 'Milky Way and galaxies.', 'undergraduate', 3, 'ASTR 300', 'astronomy'),
    ('ASTR', '430', 'Observational Astronomy', 'Telescopes and techniques.', 'undergraduate', 3, 'ASTR 300', 'astronomy'),
]

ENVS_COURSES = [
    ('ENVS', '100', 'Introduction to Environmental Studies', 'Environmental issues overview.', 'undergraduate', 3, None, 'environmental-studies'),
    ('ENVS', '200', 'Environmental Science', 'Scientific principles of environment.', 'undergraduate', 3, 'ENVS 100', 'environmental-studies'),
    ('ENVS', '210', 'Environmental Policy', 'Environmental law and policy.', 'undergraduate', 3, 'ENVS 100', 'environmental-studies'),
    ('ENVS', '300', 'Environmental Impact Assessment', 'EIA methods.', 'undergraduate', 3, 'ENVS 200', 'environmental-studies'),
    ('ENVS', '310', 'Climate Change', 'Climate science and impacts.', 'undergraduate', 3, 'ENVS 200', 'environmental-studies'),
    ('ENVS', '320', 'Sustainable Development', 'Sustainability principles.', 'undergraduate', 3, 'ENVS 200', 'environmental-studies'),
    ('ENVS', '400', 'Environmental Planning', 'Land use planning.', 'undergraduate', 3, 'ENVS 300', 'environmental-studies'),
    ('ENVS', '410', 'Conservation Biology', 'Biodiversity conservation.', 'undergraduate', 3, 'ENVS 200', 'environmental-studies'),
    ('ENVS', '420', 'Urban Ecology', 'Cities and environment.', 'undergraduate', 3, 'ENVS 200', 'environmental-studies'),
    ('ENVS', '430', 'Water Resources', 'Water management.', 'undergraduate', 3, 'ENVS 200', 'environmental-studies'),
    ('ENVS', '440', 'Energy and Environment', 'Energy systems and sustainability.', 'undergraduate', 3, 'ENVS 200', 'environmental-studies'),
    ('ENVS', '600', 'Graduate Environmental Studies', 'Graduate-level ENVS.', 'graduate', 3, None, 'environmental-studies'),
    ('ENVS', '700', 'Thesis', 'Graduate thesis research.', 'graduate', 6, None, 'environmental-studies'),
]

# Combine all science courses
SCIENCE_ENGINEERING_COURSES = (
    CSC_COURSES + MATH_COURSES + PHYS_COURSES + CHEM_COURSES + 
    BIOL_COURSES + ENGR_COURSES + EE_COURSES + GEOL_COURSES + 
    ASTR_COURSES + ENVS_COURSES
)

