-- Seed representative SFSU courses with descriptions
-- Note: Descriptions are essential for professor's search requirement (search "title + description")
INSERT INTO courses (department, course_number, title, description, credits, prerequisites, subject_id) VALUES
('CSC', '210', 'Introduction to Computer Programming', 
  'Learn fundamentals of programming using Python. Topics include variables, control structures, functions, lists, and basic algorithms. Suitable for beginners with no prior programming experience.',
  3, 'MATH 124 or equivalent', (SELECT id FROM subjects WHERE slug='computer-science')),
('CSC', '220', 'Data Structures', 
  'Study fundamental data structures including arrays, linked lists, stacks, queues, trees, and graphs. Implementation in Java with focus on algorithm complexity and efficiency.',
  3, 'CSC 210', (SELECT id FROM subjects WHERE slug='computer-science')),
('CSC', '256', 'Machine Structures', 
  'Computer organization and assembly language programming. Topics include CPU architecture, memory systems, instruction sets, and low-level programming in C and assembly.',
  3, 'CSC 220', (SELECT id FROM subjects WHERE slug='computer-science')),
('CSC', '340', 'Programming Methodology', 
  'Advanced software development using object-oriented design patterns. Java programming with emphasis on design principles, testing, debugging, and team collaboration.',
  3, 'CSC 256', (SELECT id FROM subjects WHERE slug='computer-science')),
('CSC', '412', 'Operating Systems', 
  'Operating system concepts including process management, scheduling, memory management, file systems, and concurrency. Programming projects in C and Linux.',
  3, 'CSC 340', (SELECT id FROM subjects WHERE slug='computer-science')),
('CSC', '648', 'Software Engineering Project', 
  'Full-stack web application development using agile methodologies. Team project covering requirements, design, implementation, testing, and deployment. Technologies: React, Node.js, MySQL, Git.',
  3, 'CSC 340', (SELECT id FROM subjects WHERE slug='computer-science')),
('MATH', '226', 'Calculus I', 
  'Differential calculus of functions of one variable. Topics include limits, derivatives, applications of derivatives, and introduction to integration.',
  4, 'MATH 124', (SELECT id FROM subjects WHERE slug='mathematics')),
('MATH', '227', 'Calculus II', 
  'Integral calculus and infinite series. Topics include integration techniques, applications of integrals, sequences, series, and Taylor series.',
  4, 'MATH 226', (SELECT id FROM subjects WHERE slug='mathematics')),
('PHYS', '220', 'General Physics I', 
  'Calculus-based physics covering mechanics, heat, and sound. Topics include kinematics, Newton\'s laws, energy, momentum, rotational motion, and thermodynamics.',
  3, 'MATH 226', (SELECT id FROM subjects WHERE slug='physics')),
('ACCT', '301', 'Intermediate Accounting II', 
  'Continuation of financial accounting theory and practice. Topics include long-term liabilities, stockholders\' equity, earnings per share, and accounting changes.',
  3, 'ACCT 300', (SELECT id FROM subjects WHERE slug='mathematics')), -- Mapping ACCT to Math for demo purposes if Business not exists, or just Math
('CSC', '317', 'Web Development', 
  'Modern web development covering HTML5, CSS3, JavaScript, and responsive design. Learn to build interactive websites using frameworks like Bootstrap, jQuery, and basic backend integration with Node.js.',
  3, 'CSC 210', (SELECT id FROM subjects WHERE slug='computer-science')),
('CSC', '413', 'Algorithms and Data Structures', 
  'Advanced algorithms and data structures with emphasis on efficiency and optimization. Topics include sorting algorithms, binary search trees, hash tables, graph algorithms, and dynamic programming. Implementation in Java and Python.',
  3, 'CSC 220', (SELECT id FROM subjects WHERE slug='computer-science')),
('CHEM', '115', 'General Chemistry', 
  'Fundamental principles of chemistry including atomic structure, chemical bonding, stoichiometry, and chemical reactions. Laboratory work includes experiments with acids, bases, and chemical analysis.',
  4, 'MATH 124', (SELECT id FROM subjects WHERE slug='chemistry')),
('BIOL', '230', 'Human Biology', 
  'Introduction to human anatomy and physiology. Topics include organ systems, cellular biology, genetics, and homeostasis. Focus on understanding how the human body functions.',
  3, 'None', (SELECT id FROM subjects WHERE slug='biology')),
('MATH', '325', 'Discrete Mathematics', 
  'Mathematical foundations for computer science including logic, proofs, set theory, combinatorics, graph theory, and discrete structures. Essential for understanding algorithms and complexity.',
  3, 'MATH 226', (SELECT id FROM subjects WHERE slug='mathematics'));


