#!/usr/bin/env python3
"""
setup_db.py
-----------
Database setup script for TutorConnect. Creates the database, runs all
SQL migrations, and seeds initial data. Can be run locally or in CI/CD.

Contributors: Ranjiv Jithendran, Dhvanil Bhagat

Defaults (non-secret) :
  user: app_user
  password: (none — supply via DB_PASSWORD env var, DATABASE_URL, or the prompt)
  host: 127.0.0.1
  port: 3306
  database: csc648_tutoring_platform
"""
import os
import sys
import subprocess
from getpass import getpass
from pathlib import Path
from typing import Iterable
from urllib.parse import urlparse

import pymysql
from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parent
MIGRATIONS_DIR = ROOT / "db" / "migrations"
SEED_DIR = ROOT / "db" / "seed"
ENV_PATH = ROOT / ".env"

# No hardcoded password default: supply it interactively or via the
# DB_PASSWORD / DATABASE_URL environment variables (never committed to the repo).
DEFAULTS = {
    "DB_HOST": "127.0.0.1",
    "DB_PORT": "3306",
    "DB_USER": "app_user",
    "DB_PASSWORD": "",
    "DB_NAME": "csc648_tutoring_platform",
}


def prompt_value(name: str, default: str, secret: bool = False) -> str:
    """Prompt for a value with a default; fall back to default if non-interactive."""
    existing = os.getenv(name)
    if existing:
        return existing

    if not sys.stdin.isatty():
        return default

    prompt = f"{name} [{default}]: "
    if secret:
        value = getpass(prompt)
    else:
        value = input(prompt)
    return value.strip() or default


def ensure_connection(host: str, port: int, user: str, password: str, database: str):
    """Connect to MySQL and ensure the database exists. Return a connection bound to the DB."""
    conn = pymysql.connect(
        host=host,
        port=port,
        user=user,
        password=password,
        charset="utf8mb4",
        autocommit=False,
    )
    try:
        with conn.cursor() as cursor:
            cursor.execute(
                f"CREATE DATABASE IF NOT EXISTS `{database}` "
                "CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;"
            )
        conn.commit()
        conn.select_db(database)
        return conn
    except Exception:
        conn.close()
        raise


def create_user_if_needed(admin_conn, db_user: str, db_password: str, db_name: str):
    """
    Attempt to create the database user and grant privileges.
    Requires appropriate privileges on the admin connection; failures are logged and ignored.
    """
    try:
        with admin_conn.cursor() as cursor:
            cursor.execute(
                f"CREATE USER IF NOT EXISTS '{db_user}'@'localhost' IDENTIFIED BY %s;",
                (db_password,),
            )
            cursor.execute(
                f"GRANT ALL PRIVILEGES ON `{db_name}`.* TO '{db_user}'@'localhost';"
            )
            cursor.execute("FLUSH PRIVILEGES;")
        admin_conn.commit()
        print(f"[INFO] Ensured user '{db_user}' with access to '{db_name}'.")
    except Exception as exc:
        print(f"[WARN] Could not create/assign user '{db_user}': {exc}")


def execute_sql_file(cursor, filepath: Path):
    """Execute all SQL statements in a file (split on semicolons)."""
    sql_content = filepath.read_text(encoding="utf-8")
    statements = [s.strip() for s in sql_content.split(";") if s.strip()]
    for stmt in statements:
        cursor.execute(stmt)


def run_sql_files(conn, files: Iterable[Path], label: str):
    """Run a sequence of SQL files inside a single transaction."""
    if not files:
        print(f"[WARN] No {label} files found.")
        return

    with conn.cursor() as cursor:
        cursor.execute("SET FOREIGN_KEY_CHECKS=0;")
        for sql_file in files:
            print(f"[{label}] {sql_file.name}")
            execute_sql_file(cursor, sql_file)
        cursor.execute("SET FOREIGN_KEY_CHECKS=1;")
    conn.commit()


def write_env_file(database_url: str):
    """Write .env with DATABASE_URL if it does not already exist."""
    if ENV_PATH.exists():
        print(f"[INFO] .env already exists at {ENV_PATH}, leaving unchanged.")
        return

    content = (
        "# Generated by setup_db.py\n"
        f"DATABASE_URL={database_url}\n"
        "API_ENV=development\n"
        "API_DEBUG=True\n"
    )
    ENV_PATH.write_text(content, encoding="utf-8")
    print(f"[INFO] Wrote .env with DATABASE_URL to {ENV_PATH}")


def main() -> int:
    load_dotenv()

    host = prompt_value("DB_HOST", DEFAULTS["DB_HOST"])
    port = int(prompt_value("DB_PORT", DEFAULTS["DB_PORT"]))
    user = prompt_value("DB_USER", DEFAULTS["DB_USER"])
    password = prompt_value("DB_PASSWORD", DEFAULTS["DB_PASSWORD"], secret=True)
    db_name = prompt_value("DB_NAME", DEFAULTS["DB_NAME"])

    # First try with provided credentials
    try:
        connection = ensure_connection(host, port, user, password, db_name)
    except pymysql.err.OperationalError as exc:
        # Ask to elevate using an admin account (e.g., root) to bootstrap user/db
        code = exc.args[0] if exc.args else None
        print(f"[WARN] Could not connect/create database with provided credentials: {exc}")
        if code == 1045 or sys.stdin.isatty():
            elevate = "n"
            if sys.stdin.isatty():
                elevate = input("Use admin (e.g., root) to create the user/db? [y/N]: ").strip().lower() or "n"
            if elevate == "y":
                # First attempt via TCP admin credentials
                admin_user = prompt_value("ADMIN_USER", "root")
                admin_password = prompt_value("ADMIN_PASSWORD", "", secret=True)
                tcp_bootstrap_failed = False
                try:
                    admin_conn = pymysql.connect(
                        host=host,
                        port=port,
                        user=admin_user,
                        password=admin_password or None,
                        charset="utf8mb4",
                        autocommit=False,
                    )
                    with admin_conn.cursor() as cursor:
                        cursor.execute(
                            f"CREATE DATABASE IF NOT EXISTS `{db_name}` "
                            "CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;"
                        )
                        cursor.execute(
                            f"CREATE USER IF NOT EXISTS '{user}'@'localhost' IDENTIFIED BY %s;",
                            (password,),
                        )
                        cursor.execute(
                            f"GRANT ALL PRIVILEGES ON `{db_name}`.* TO '{user}'@'localhost';"
                        )
                        cursor.execute("FLUSH PRIVILEGES;")
                    admin_conn.commit()
                    admin_conn.close()
                    print(f"[INFO] Created DB '{db_name}' and user '{user}' via admin (TCP).")
                    connection = ensure_connection(host, port, user, password, db_name)
                except Exception as inner_exc:
                    tcp_bootstrap_failed = True
                    print(f"[WARN] Admin bootstrap via TCP failed: {inner_exc}")

                if tcp_bootstrap_failed:
                    # Try sudo mysql (socket auth), useful when root uses auth_socket
                    if sys.stdin.isatty():
                        sudo_pw = getpass("Sudo password (for sudo mysql): ")
                        sql = (
                            f"CREATE DATABASE IF NOT EXISTS `{db_name}` "
                            "CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci; "
                            f"CREATE USER IF NOT EXISTS '{user}'@'localhost' IDENTIFIED BY '{password}'; "
                            f"GRANT ALL PRIVILEGES ON `{db_name}`.* TO '{user}'@'localhost'; "
                            "FLUSH PRIVILEGES;"
                        )
                        try:
                            run_sudo_mysql(sql, sudo_pw)
                            print(f"[INFO] Created DB '{db_name}' and user '{user}' via sudo mysql.")
                            connection = ensure_connection(host, port, user, password, db_name)
                        except Exception as sudo_exc:
                            print(f"[ERROR] Admin bootstrap via sudo mysql failed: {sudo_exc}")
                            return 1
                    else:
                        print("[ERROR] Cannot prompt for sudo password in non-interactive mode.")
                        return 1
            else:
                print("Tip: ensure the user has permissions, or rerun with admin bootstrap.")
                return 1
        else:
            print("Tip: ensure the user has permissions, or rerun with admin bootstrap.")
            return 1
    except Exception as exc:
        print(f"[ERROR] Could not connect/create database with provided credentials: {exc}")
        return 1

    # Run migrations
    migrations = sorted(MIGRATIONS_DIR.glob("*.sql"))
    print(f"[INFO] Running {len(migrations)} migrations from {MIGRATIONS_DIR}...")
    run_sql_files(connection, migrations, label="MIGRATION")

    # Run seeds if present
    seed_files = sorted(SEED_DIR.glob("*.sql"))
    if seed_files:
        print(f"[INFO] Running {len(seed_files)} seed files from {SEED_DIR}...")
        run_sql_files(connection, seed_files, label="SEED")
    else:
        print("[INFO] No seed files found; skipping.")

    connection.close()

    # Write .env if missing
    database_url = f"mysql+pymysql://{user}:{password}@{host}:{port}/{db_name}"
    write_env_file(database_url)

    print("[SUCCESS] Database setup complete.")
    return 0


def run_sudo_mysql(sql: str, sudo_password: str) -> None:
    """
    Execute SQL using `sudo mysql -e` via stdin password.
    Falls back to local socket auth; ignores host/port.
    """
    cmd = ["sudo", "-S", "mysql", "-e", sql]
    proc = subprocess.run(
        cmd,
        input=f"{sudo_password}\n",
        text=True,
        capture_output=True,
    )
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr.strip() or f"sudo mysql failed with code {proc.returncode}")


if __name__ == "__main__":
    sys.exit(main())
